os: linux
version: 0.0
files: 
  - 
    destination: /var/www/rpgchef_next/build
    source: build
  - 
    destination: /var/www/rpgchef_next/node_modules
    source: node_modules
hooks:
    AfterInstall:
      -
        location: scripts/updatelive.sh
        runas: root
